### ISSUE TITLE
neovim0.5 release, kabouzeid/nvim-lspinstall to install java lsp, it's a bit slow when quit java file

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [mfussenegger/nvim-jdtls#101]
i know it's not nvim-jdtls's problem, but does someone encounter it ?

**Comment by mfussenegger** [comment]
How long is a bit slow? 200ms, 1sec, 5sec?
Neovim waits for the lsp process to exit before it closes,  so some delay compared to not using a language server is expected.

I also think I saw some improvements in the eclipse.jdt.ls repo in regards to shutting down.

**Comment by FinallyFinancialFreedom** [comment]
about 1s, neovim 0.4.4 and coc.vim doesn't slow when quit.

**Comment by mfussenegger** [comment]
It turns out that currently neovim has a `500ms` max wait time for the language server to exit cleanly before it goes on with the termination process. If the server exists faster neovim would shutdown faster as well.

`eclipse.jdtls` would actually sometimes take even longer to exit cleanly:

```
[2021-07-08T15:11:18+0200] "client.stop", 0.030007, "jdt.ls"
[2021-07-08T15:11:18+0200] "shutdown response after", 2.136298
[2021-07-08T15:11:19+0200] "on exit called", 1417.407935
[2021-07-08T15:11:19+0200] "vim_exit_handler took", 1419.992915
```

(durations here are in ms)

I'll bring this up with the other neovim/lsp contributors and close it here, since I can't do anything about it in nvim-jdtls.

**Comment by FinallyFinancialFreedom** [comment]
thank you very much.
