### ISSUE TITLE
How to look for external dependencies?

### ISSUE THREAD

**Issue by limyanchong** [mfussenegger/nvim-jdtls#106]
The configurations needed are overwhelming for me. I think I got nvim-jdtls to work but:
Does nvim-jdtls configure to look for the dependencies in Maven and Gradle caches ~/.m2 and ~/.gradle?
If not, how do I do it?

**Comment by mfussenegger** [comment]
eclipse.jdt.ls tries to load the dependencies based on the maven pom.xml or gradle build files.
Where maven and gradle looks for the dependencies depends on how gradle or maven are configuration.

**Comment by limyanchong** [comment]
I am new to Java development. I think it will be cool to get it works in nvim.
I used IntelliJ IDEA with Vim plugin. My company develops plugin for a software.
In IntelliJ IDEA,
1. Inside one of the plugin source code files, when I press "gd" on one of the software classes, it will go the the definition of the software jar file inside ~/.gradle cache.
2. The IntelliJ IDEA project was setup using `./gradlew openidea`.

I am not sure if this information is enough for anyone who can give a hand on making it work like that with nvim-jdtls. I try my best.
I probably need to stuck with IntelliJ IDEA until I know more about how all these Gradle/Maven stuffs fit together.

**Comment by mfussenegger** [comment]
If the depencencies are declared in the `build.gradle` files, eclipse.jdt.ls should pick them up.

But it is important that the `root_dir` is set to the root of your project directory. Otherwise it won't be able to load the project correctly.

If `:lua require('jdtls').compile('full')` runs without error, it is usually an indication that the project got loaded correctly, and otherwise it might give some pointers on what's wrong.
