### ISSUE TITLE
Add in readme how to configure it using LSPInstall

### ISSUE THREAD

**Issue by wviana** [mfussenegger/nvim-jdtls#156]
### Problem Statement

Hello, 
I've installed the jdtls using lspinstall plugin.
It was the easiest way that I've found to get jdtls working.  But I got it working just with nvim-lsp,
Would be nice to have in readme how to configure this plugin installing jdtls by using lspinstall.

**Comment by mfussenegger** [comment]
There is nothing special about using lspinstall for the installation step. You'll stilll have to follow https://github.com/mfussenegger/nvim-jdtls#configuration and adjust the cmd according to where lspinstall places the eclipse.jdt.ls package.

**Comment by zhongjis** [comment]
came by this post while trying to figure out a way to use lsp-installer with nvim-jdtls. 

don't think should be put in README but still worth adding here as [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) is kinda useful.

Instead of manually finding/inputting everything in [mfussenegger/nvim-jdtls#configuration](https://github.com/mfussenegger/nvim-jdtls#configuration) mentioned, `nvim-lsp-installer' has a pretty neat auto generated [lsp-installer-jdtls-config](https://github.com/williamboman/nvim-lsp-installer/blob/main/lua/nvim-lsp-installer/servers/jdtls/init.lua). I decided to just use that instead of writing my own.

the following is my lsp config
```lua
-- LSP settings
local default_on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
    require('zhongjis.mapping').lsp_attach_mapping(bufnr)
end

-- nvim-cmp supports additional completion capabilities
local capabilities =require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

-- Enable the following language servers
local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
    local opts = {
        on_attach = default_on_attach,
        capabilities = capabilities
    }

    if server.name == "jdtls" then
        local available, jdtls = lsp_installer.get_server("jdtls")
        if available then
            local default_opts = jdtls._default_options
            opts.settings = {
                java = {
                    signatureHelp = {
                        enabled = true
                    }
                }
            }
            local combined_opts = vim.tbl_deep_extend("force", default_opts, opts)
            require('jdtls').start_or_attach(combined_opts)
        else
            print('[LSP] error, cannot find jdtls server in nvim-lsp-installer')
        end
    else
        -- This setup() function is exactly the same as lspconfig's setup function.
        -- Refer to https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
        server:setup(opts)
    end
end)
```

what do you guys think? @mfussenegger @wviana

**Comment by punowo** [comment]
@zhongjis Hi, I took a look at your dotfiles and tried to copy the parts about jdtls into my own lua configuration. 
Do you also have the problem where jdtls gets started for literally any folder despite it not being a java project ?
