### ISSUE TITLE
Code actions entries duplicated, organize imports doesn't always work 

### ISSUE THREAD

**Issue by abenz1267** [mfussenegger/nvim-jdtls#235]
### Eclipse.jdt.ls version

latest

### Steps to Reproduce

Opening code actions, doing "organize imports"

### Expected Result

Code actions only being present once.

Organize imports always working.

### Actual Result

the opposite

I'm not sure if this is an actual issue with nvim-jdtls or jdtls itself. organize imports not always working is certainly a bit annoying.

side note: what's the best practice here to organise import on save? jdtls has "saveActions -> organizeImports" but that doesn't work with nvim-jdtls. Having an autocmd with BufWritePre? Or should "saveActions" in theory work?

**Comment by mfussenegger** [comment]
Duplicate entries is/was a jdtls bug. See https://github.com/eclipse/eclipse.jdt.ls/pull/1982

Do you have a reproduction for the organize imports not working? I haven't noticed that.

**Comment by abenz1267** [comment]
i actually just tried to do a screen recording when noticing it seems to be a problem with fzf-lua.

Open file > organize imports > works. Open another file > organize imports > doesn't work.

I'll make an issue there.

**Comment by abenz1267** [comment]
I opened an issue for fzf-lua here https://github.com/ibhagwan/fzf-lua/issues/319

The problem seems to be related to jdtls though, as gopls doesn't face the same issue.

**Comment by ibhagwan** [comment]
Without jumping to conclusions this may **or may not be related** to `nvim-jdtls`, I believe "Organize Imports"  ends up calling `vim.lsp.util.apply_workspace_edit` with the approperiate code action edit, if we wish to debug this further I can either write a few lines of code to run the API directly (without the fzf-lua interface) or have a local version of the plugin and add a few debug dumps in the process.

Looking at [the recording from @abenz1267](https://drive.google.com/file/d/147kHAa30BuQABqMYvrGlBy_ba6soCJbY/view?usp=sharing) it shows there are indeed code actions, unless there is a bug in fzf-lua (not ruling that out at all) the next step after selecting a code action would be running `vim.lsp.util.apply_workspace_edit`.

Note that this is not the only way to apply code actions with fzf-lua, since https://github.com/ibhagwan/fzf-lua/issues/314 it's also possible to override `vim.ui.select` with `:FzfLua register_ui_select` which @abenz1267 confirmed doesn't have this issue.

Is there a way for me to test `nvim-jdtls` without having java runtime installed?

**Comment by abenz1267** [comment]
> Note that this is not the only way to apply code actions with fzf-lua, since [ibhagwan/fzf-lua#314](https://github.com/ibhagwan/fzf-lua/issues/314) it's also possible to override `vim.ui.select` with `:FzfLua register_ui_select` which @abenz1267 confirmed doesn't have this issue.

Just to be clear here: the problem is present with `FzfLua register_ui_select`. Using the native vim.ui.select does not cause this issue. Only when using FzfLua's ui-select implementation.

**Comment by ibhagwan** [comment]
>Just to be clear here: the problem is present with FzfLua register_ui_select.

Did you mean **not present**?

I posted test code in the corresponding [fzf-lua issue #314](https://github.com/ibhagwan/fzf-lua/issues/319#issuecomment-1017868140), please run it and if you don't get an output that probably means the issue is in `fzf-lua`.

If you do get an output in `:messages` in both files it means the issue is not with fzf-lua and you can post here so @mfussenegger can take a look.

**Comment by ibhagwan** [comment]
>Organize imports doesn't always work

Confirmed to be an issue with `fzf-lua`, fixed.

>Code actions entries duplicated

This may be a different issue.
