### ISSUE TITLE
How to get extract_method working?

### ISSUE THREAD

**Issue by jakobkhansen** [mfussenegger/nvim-jdtls#47]
Hello again,

I'm trying to get code actions to work and I'm struggling a bit to understand how the extract_method behaviour works. I assume it should be possible to mark a selection in visual mode and then run the code action "Extract to method", but this always gives me the result "No selection found that could be extracted". It does however work in some weird situations while in normal mode, but that will only extract a single line, which is not what I want. Any idea what I'm doing wrong / what I need to configure?

**Comment by mfussenegger** [comment]
It turned out that I introduced a regression when I added the `inferSelection` support.
I just merged a fix that should get the `extract_method` functionality working again.

https://github.com/mfussenegger/nvim-jdtls/pull/52

You need to have a visual mode mapping for either `<Esc><Cmd>lua require'jdtls'.code_action(true, 'refactor')<CR>` if you want to trigger it via code action, or `<Esc><Cmd>lua require('jdtls').extract_method(true)<CR>` if you want to trigger it directly.

**Comment by jakobkhansen** [comment]
Works great, thanks.
