### ISSUE TITLE
Question: Using completion.nvim

### ISSUE THREAD

**Issue by mherna** [mfussenegger/nvim-jdtls#62]
Hi, I am trying to do my initial setup, I saw your dotfiles @mfussenegger and liked the way you trigger completion using  `api.nvim_buf_set_keymap(bufnr, "i", "<c-n>", "<Cmd>lua require('lsp-ext').trigger_completion()<CR>", opts)`.

But I don't know if it's possible to make it do something similar to the `on_attach` function of `nvim-lua/completion-nvim`. I tried just adding ` completion.on_attach(client)` ... obv using the local require... but when I tested it on a java buffer the completion, it adds `Buffer - java.nio` instead of the expected `Buffer`. Meanwhile, your completion correctly selects `Buffer` and, if needed, adds the required import.

**Comment by mfussenegger** [comment]
>  but when I tested it on a java buffer the completion, it adds Buffer - java.nio instead of the expected Buffer

I think this is due to it being part of the `label` of the completion responses from the server. 
I customized the `text_document_completion_list_to_complete_items` function to avoid that. The relevant parts:

https://github.com/mfussenegger/dotfiles/blob/09909083c369c0d90f3eaccf47ad5bc81a1f1046/vim/.config/nvim/lua/lsp-ext.lua#L48-L70

https://github.com/mfussenegger/dotfiles/blob/09909083c369c0d90f3eaccf47ad5bc81a1f1046/vim/.config/nvim/lua/lsp-ext.lua#L273-L275

There might be an option in `nvim-lua/completion-nvim` to control that was well, otherwise you might want to check out https://github.com/hrsh7th/nvim-compe

**Comment by mherna** [comment]
Thanks, your reply was super useful!

For anyone trying to setup completion to work you can use `nvim-lua/completion-nvim` function `customize_buf_label` and use the relevant lines mentioned by @mfussenegger and do something like:

```lua
completion.customize_buf_label({require('lsp-ext').setup()})
```
